basePath: /
definitions:
  models.User:
    properties:
      id:
        type: string
      username:
        type: string
    type: object
info:
  contact:
    email: justine.bachelard@ext.uca.fr
    name: Justine Bachelard.
  description: API to manage users.
  title: middleware/users
  version: 1.0.0
paths:
  /users:
    get:
      description: Get users.
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "500":
          description: Something went wrong
      summary: Get users.
      tags:
      - users
    post:
      description: Creates a user with username.
      parameters:
      - description: Username
        in: body
        name: username
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "422":
          description: Cannot parse username
        "500":
          description: Something went wrong
      summary: Creates a user with username.
      tags:
      - users
  /users/{id}:
    delete:
      description: Delete a user.
      parameters:
      - description: User UUID formatted ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
        "422":
          description: Cannot parse id
        "500":
          description: Something went wrong
      summary: Delete a user.
      tags:
      - users
    get:
      description: Get a user.
      parameters:
      - description: User UUID formatted ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "422":
          description: Cannot parse id
        "500":
          description: Something went wrong
      summary: Get a user.
      tags:
      - users
    put:
      description: Update a user.
      parameters:
      - description: User UUID formatted ID
        in: path
        name: id
        required: true
        type: string
      - description: User username
        in: body
        name: username
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
        "422":
          description: Cannot parse id
        "500":
          description: Something went wrong
      summary: Update a user.
      tags:
      - users
schemes:
- http
swagger: "2.0"
